version: '2'

services:

  receive_image:
    build: ./receive_image/
    image: receive_image
    container_name: receive_image
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  resizing_image:
    build: ./resizing_image/
    image: resizing_image
    container_name: resizing_image
    restart: always
#    volumes:
#      - resizing_image:/home/resizing_image
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq_images
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./data:/var/lib/rabbitmq/mnesia/"

#volumes:
#  resizing_image:
#    external: true
